export const monkeys = [
    "arbre-1.svg",
    "arbre-2.svg",
    "arbre-3.svg",
    "arbre-4.svg",
    "arbre-5.svg",
    "arbre-6.svg",
    "arbre-7.svg",
    "arbre-8.svg",
    "arbre-9.svg",
    "gauche-1.svg",
    "gauche-2.svg",
    "gauche-3.svg",
    "gauche-4.svg",
    "droite-1.svg",
    "droite-2.svg",
    "droite-3.svg",
    "droite-4.svg"
];    
